export interface Product {
    id: string;
    name: string;
    description: string;
    price: number;
    image: string;
    category: string;
    slug: string;
}

export interface Category {
    id: string;
    name: string;
    slug: string;
    description: string;
    image: string;
}

// Sample data - in a real app, this would come from a database or CMS
export const categories: Category[] = [
    {
        id: '1',
        name: 'Electronics',
        slug: 'electronics',
        description: 'Latest gadgets and electronics',
        image: '/images/electronics.jpg',
    },
    {
        id: '2',
        name: 'Clothing',
        slug: 'clothing',
        description: 'Fashionable clothing for everyone',
        image: '/images/clothing.jpg',
    },
    {
        id: '3',
        name: 'Home & Garden',
        slug: 'home-garden',
        description: 'Everything for your home',
        image: '/images/home-garden.jpg',
    },
];

export const products: Product[] = [
    {
        id: '1',
        name: 'Wireless Headphones',
        description: 'High-quality wireless headphones with noise cancellation',
        price: 199.99,
        image: '/images/headphones.jpg',
        category: 'electronics',
        slug: 'wireless-headphones',
    },
    {
        id: '2',
        name: 'Smartphone',
        description: 'Latest smartphone with advanced features',
        price: 899.99,
        image: '/images/smartphone.jpg',
        category: 'electronics',
        slug: 'smartphone',
    },
    {
        id: '3',
        name: '4K Smart TV',
        description: 'Ultra HD Smart TV with vibrant colors and smart features',
        price: 1299.99,
        image: '/images/smart-tv.jpg',
        category: 'electronics',
        slug: '4k-smart-tv',
    },
    {
        id: '4',
        name: 'Bluetooth Speaker',
        description: 'Portable Bluetooth speaker with deep bass',
        price: 99.99,
        image: '/images/bluetooth-speaker.jpg',
        category: 'electronics',
        slug: 'bluetooth-speaker',
    },
    {
        id: '5',
        name: 'Laptop',
        description: 'Lightweight laptop with powerful performance',
        price: 1199.99,
        image: '/images/laptop.jpg',
        category: 'electronics',
        slug: 'laptop',
    },
    {
        id: '6',
        name: 'Smartwatch',
        description: 'Track your fitness and receive notifications on your wrist',
        price: 249.99,
        image: '/images/smartwatch.jpg',
        category: 'electronics',
        slug: 'smartwatch',
    },
    {
        id: '7',
        name: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with long battery life',
        price: 39.99,
        image: '/images/wireless-mouse.jpg',
        category: 'electronics',
        slug: 'wireless-mouse',
    },
    {
        id: '8',
        name: 'Mechanical Keyboard',
        description: 'RGB backlit mechanical keyboard for gamers',
        price: 129.99,
        image: '/images/mechanical-keyboard.jpg',
        category: 'electronics',
        slug: 'mechanical-keyboard',
    },
    {
        id: '9',
        name: 'Gaming Console',
        description: 'Next-gen gaming console with immersive graphics',
        price: 599.99,
        image: '/images/gaming-console.jpg',
        category: 'electronics',
        slug: 'gaming-console',
    },
    {
        id: '10',
        name: 'Cotton T-Shirt',
        description: 'Comfortable cotton t-shirt in various colors',
        price: 29.99,
        image: '/images/tshirt.jpg',
        category: 'clothing',
        slug: 'cotton-tshirt',
    },
    {
        id: '11',
        name: 'Denim Jeans',
        description: 'Classic slim-fit denim jeans',
        price: 59.99,
        image: '/images/jeans.jpg',
        category: 'clothing',
        slug: 'denim-jeans',
    },
    {
        id: '12',
        name: 'Hoodie',
        description: 'Soft and warm hoodie perfect for chilly days',
        price: 49.99,
        image: '/images/hoodie.jpg',
        category: 'clothing',
        slug: 'hoodie',
    },
    {
        id: '13',
        name: 'Leather Jacket',
        description: 'Stylish leather jacket with modern fit',
        price: 199.99,
        image: '/images/leather-jacket.jpg',
        category: 'clothing',
        slug: 'leather-jacket',
    },
    {
        id: '14',
        name: 'Sneakers',
        description: 'Lightweight sneakers for everyday comfort',
        price: 89.99,
        image: '/images/sneakers.jpg',
        category: 'clothing',
        slug: 'sneakers',
    },
    {
        id: '15',
        name: 'Summer Dress',
        description: 'Elegant floral summer dress for women',
        price: 69.99,
        image: '/images/summer-dress.jpg',
        category: 'clothing',
        slug: 'summer-dress',
    },
    {
        id: '16',
        name: 'Wool Scarf',
        description: 'Soft wool scarf to keep you warm in winter',
        price: 24.99,
        image: '/images/scarf.jpg',
        category: 'clothing',
        slug: 'wool-scarf',
    },
    {
        id: '17',
        name: 'Baseball Cap',
        description: 'Adjustable cotton cap for casual wear',
        price: 19.99,
        image: '/images/cap.jpg',
        category: 'clothing',
        slug: 'baseball-cap',
    },
    {
        id: '18',
        name: 'Winter Coat',
        description: 'Insulated winter coat with hood',
        price: 179.99,
        image: '/images/winter-coat.jpg',
        category: 'clothing',
        slug: 'winter-coat',
    },

    {
        id: '19',
        name: 'Garden Tools Set',
        description: 'Complete set of gardening tools',
        price: 149.99,
        image: '/images/garden-tools.jpg',
        category: 'home-garden',
        slug: 'garden-tools-set',
    },
    {
        id: '20',
        name: 'Scented Candle',
        description: 'Relaxing lavender-scented candle for your home',
        price: 14.99,
        image: '/images/scented-candle.jpg',
        category: 'home-garden',
        slug: 'scented-candle',
    },
    {
        id: '21',
        name: 'Decorative Plant',
        description: 'Artificial decorative plant in ceramic pot',
        price: 29.99,
        image: '/images/decorative-plant.jpg',
        category: 'home-garden',
        slug: 'decorative-plant',
    },
    {
        id: '22',
        name: 'Wall Clock',
        description: 'Minimalist wall clock for living room',
        price: 39.99,
        image: '/images/wall-clock.jpg',
        category: 'home-garden',
        slug: 'wall-clock',
    },
    {
        id: '23',
        name: 'Coffee Maker',
        description: 'Automatic drip coffee maker with timer',
        price: 89.99,
        image: '/images/coffee-maker.jpg',
        category: 'home-garden',
        slug: 'coffee-maker',
    },
    {
        id: '24',
        name: 'Vacuum Cleaner',
        description: 'Powerful cordless vacuum cleaner',
        price: 249.99,
        image: '/images/vacuum-cleaner.jpg',
        category: 'home-garden',
        slug: 'vacuum-cleaner',
    },
    {
        id: '25',
        name: 'Cookware Set',
        description: 'Non-stick cookware set for everyday use',
        price: 179.99,
        image: '/images/cookware-set.jpg',
        category: 'home-garden',
        slug: 'cookware-set',
    },
    {
        id: '26',
        name: 'Table Lamp',
        description: 'Modern LED table lamp with adjustable brightness',
        price: 49.99,
        image: '/images/table-lamp.jpg',
        category: 'home-garden',
        slug: 'table-lamp',
    },
    {
        id: '27',
        name: 'Rug Carpet',
        description: 'Soft rug carpet for your living space',
        price: 99.99,
        image: '/images/rug.jpg',
        category: 'home-garden',
        slug: 'rug-carpet',
    },
];