export interface Product {
    id: string;
    name: string;
    description: string;
    price: number;
    originalPrice?: number;
    image: string;
    category: string;
    slug: string;
    featured: boolean;
    onSale: boolean;
    rating?: number;
    stock: number;
}



export const products: Product[] = [
    {
        id: '1',
        name: 'Wireless Headphones',
        description: 'High-quality wireless headphones with noise cancellation',
        price: 199.99,
        originalPrice: 249.99,
        image: '/images/headphones.jpg',
        category: 'electronics',
        slug: 'wireless-headphones',
        featured: true,
        onSale: true,
        rating: 4.8,
        stock: 15
    },
    {
        id: '2',
        name: 'Smartphone',
        description: 'Latest smartphone with advanced features',
        price: 899.99,
        image: '/images/smartphone.jpg',
        category: 'electronics',
        slug: 'smartphone-pro',
        featured: true,
        onSale: false,
        rating: 4.9,
        stock: 8
    },
    {
        id: '3',
        name: '4K Smart TV',
        description: 'Ultra HD Smart TV with vibrant colors and smart features',
        price: 1299.99,
        originalPrice: 1599.99,
        image: '/images/smart-tv.jpg',
        category: 'electronics',
        slug: '4k-smart-tv',
        featured: true,
        onSale: true,
        rating: 4.7,
        stock: 5
    },
    {
        id: '4',
        name: 'Bluetooth Speaker',
        description: 'Portable Bluetooth speaker with deep bass',
        price: 99.99,
        image: '/images/bluetooth-speaker.jpg',
        category: 'electronics',
        slug: 'bluetooth-speaker',
        featured: false,
        onSale: false,
        rating: 4.4,
        stock: 20
    },
    {
        id: '5',
        name: 'Laptop',
        description: 'Lightweight laptop with powerful performance',
        price: 1199.99,
        image: '/images/laptop.jpg',
        category: 'electronics',
        slug: 'laptop',
        featured: true,
        onSale: false,
        rating: 4.6,
        stock: 12
    },
    {
        id: '6',
        name: 'Smartwatch',
        description: 'Track your fitness and receive notifications on your wrist',
        price: 249.99,
        image: '/images/smartwatch.jpg',
        category: 'electronics',
        slug: 'smartwatch',
        featured: false,
        onSale: false,
        rating: 4.2,
        stock: 30
    },
    {
        id: '7',
        name: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with long battery life',
        price: 39.99,
        image: '/images/wireless-mouse.jpg',
        category: 'electronics',
        slug: 'wireless-mouse',
        featured: false,
        onSale: false,
        rating: 4.1,
        stock: 40
    },
    {
        id: '8',
        name: 'Mechanical Keyboard',
        description: 'RGB backlit mechanical keyboard for gamers',
        price: 129.99,
        image: '/images/mechanical-keyboard.jpg',
        category: 'electronics',
        slug: 'mechanical-keyboard',
        featured: true,
        onSale: false,
        rating: 4.5,
        stock: 22
    },
    {
        id: '9',
        name: 'Gaming Console',
        description: 'Next-gen gaming console with immersive graphics',
        price: 599.99,
        image: '/images/gaming-console.jpg',
        category: 'electronics',
        slug: 'gaming-console',
        featured: true,
        onSale: false,
        rating: 4.9,
        stock: 7
    },
    {
        id: '10',
        name: 'Cotton T-Shirt',
        description: 'Comfortable cotton t-shirt in various colors',
        price: 29.99,
        originalPrice: 39.99,
        image: '/images/tshirt.jpg',
        category: 'clothing',
        slug: 'cotton-tshirt',
        featured: false,
        onSale: true,
        rating: 4.3,
        stock: 50
    },
    {
        id: '11',
        name: 'Denim Jeans',
        description: 'Classic slim-fit denim jeans',
        price: 59.99,
        image: '/images/jeans.jpg',
        category: 'clothing',
        slug: 'denim-jeans',
        featured: true,
        onSale: false,
        rating: 4.7,
        stock: 25
    },
    {
        id: '11',
        name: 'Designer Hoodie',
        description: 'Premium quality hoodie with unique design',
        price: 79.99,
        image: '/images/hoodie.jpg',
        category: 'clothing',
        slug: 'designer-hoodie',
        featured: true,
        onSale: false,
        rating: 4.7,
        stock: 25
    },
    {
        id: '13',
        name: 'Leather Jacket',
        description: 'Stylish leather jacket with modern fit',
        price: 199.99,
        image: '/images/leather-jacket.jpg',
        category: 'clothing',
        slug: 'leather-jacket',
        featured: false,
        onSale: false,
        rating: 4.8,
        stock: 10
    },
    {
        id: '14',
        name: 'Sneakers',
        description: 'Lightweight sneakers for everyday comfort',
        price: 89.99,
        image: '/images/sneakers.jpg',
        category: 'clothing',
        slug: 'sneakers',
        featured: true,
        onSale: false,
        rating: 4.5,
        stock: 35
    },
    {
        id: '15',
        name: 'Summer Dress',
        description: 'Elegant floral summer dress for women',
        price: 69.99,
        originalPrice: 89.99,
        image: '/images/summer-dress.jpg',
        category: 'clothing',
        slug: 'summer-dress',
        featured: true,
        onSale: true,
        rating: 4.5,
        stock: 18
    },
    {
        id: '16',
        name: 'Wool Scarf',
        description: 'Soft wool scarf to keep you warm in winter',
        price: 24.99,
        image: '/images/scarf.jpg',
        category: 'clothing',
        slug: 'wool-scarf',
        featured: false,
        onSale: false,
        rating: 4.3,
        stock: 40
    },
    {
        id: '17',
        name: 'Baseball Cap',
        description: 'Adjustable cotton cap for casual wear',
        price: 19.99,
        image: '/images/cap.jpg',
        category: 'clothing',
        slug: 'baseball-cap',
        featured: false,
        onSale: false,
        rating: 4.0,
        stock: 60
    },
    {
        id: '18',
        name: 'Winter Coat',
        description: 'Insulated winter coat with hood',
        price: 179.99,
        image: '/images/winter-coat.jpg',
        category: 'clothing',
        slug: 'winter-coat',
        featured: true,
        onSale: false,
        rating: 4.6,
        stock: 14
    },

    {
        id: '19',
        name: 'Garden Tools Set',
        description: 'Complete set of gardening tools',
        price: 149.99,
        originalPrice: 199.99,
        image: '/images/garden-tools.jpg',
        category: 'home-garden',
        slug: 'garden-tools-set',
        featured: true,
        onSale: true,
        rating: 4.8,
        stock: 10
    },
    {
        id: '20',
        name: 'Scented Candle Set',
        description: 'Luxury scented candles in elegant packaging',
        price: 34.99,
        image: '/images/scented-candle.jpg',
        category: 'home-garden',
        slug: 'scented-candle-set',
        featured: true,
        onSale: false,
        rating: 4.6,
        stock: 30
    },
    {
        id: '21',
        name: 'Decorative Plant',
        description: 'Artificial decorative plant in ceramic pot',
        price: 29.99,
        image: '/images/decorative-plant.jpg',
        category: 'home-garden',
        slug: 'decorative-plant',
        featured: false,
        onSale: false,
        rating: 4.2,
        stock: 25
    },
    {
        id: '22',
        name: 'Wall Clock',
        description: 'Minimalist wall clock for living room',
        price: 39.99,
        image: '/images/wall-clock.jpg',
        category: 'home-garden',
        slug: 'wall-clock',
        featured: false,
        onSale: false,
        rating: 4.3,
        stock: 20
    },
    {
        id: '23',
        name: 'Coffee Maker Deluxe',
        description: 'Automatic drip coffee maker with timer and grinder',
        price: 89.99,
        originalPrice: 129.99,
        image: '/images/coffee-maker.jpg',
        category: 'home-garden',
        slug: 'coffee-maker-deluxe',
        featured: false,
        onSale: true,
        rating: 4.4,
        stock: 15
    },
    {
        id: '24',
        name: 'Vacuum Cleaner',
        description: 'Powerful cordless vacuum cleaner',
        price: 249.99,
        image: '/images/vacuum-cleaner.jpg',
        category: 'home-garden',
        slug: 'vacuum-cleaner',
        featured: true,
        onSale: false,
        rating: 4.5,
        stock: 18
    },
    {
        id: '25',
        name: 'Cookware Set',
        description: 'Non-stick cookware set for everyday use',
        price: 179.99,
        image: '/images/cookware-set.jpg',
        category: 'home-garden',
        slug: 'cookware-set',
        featured: true,
        onSale: false,
        rating: 4.7,
        stock: 12
    },
    {
        id: '26',
        name: 'Table Lamp',
        description: 'Modern LED table lamp with adjustable brightness',
        price: 49.99,
        image: '/images/table-lamp.jpg',
        category: 'home-garden',
        slug: 'table-lamp',
        featured: false,
        onSale: false,
        rating: 4.3,
        stock: 28
    },
    {
        id: '27',
        name: 'Rug Carpet',
        description: 'Soft rug carpet for your living space',
        price: 99.99,
        image: '/images/rug.jpg',
        category: 'home-garden',
        slug: 'rug-carpet',
        featured: true,
        onSale: false,
        rating: 4.6,
        stock: 10
    },
];