import { Product } from "@/types/product";

export const products: Product[] = [
    {
        id: '1',
        name: 'Wireless Headphones',
        description: 'High-quality wireless headphones with noise cancellation',
        price: 199.99,
        originalPrice: 249.99,
        image: '/images/headphones.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'wireless-headphones',
        featured: true,
        onSale: true,
        rating: 4.8,
        reviewCount: 124,
        stock: 15,
        createdAt: new Date('2024-01-15').toISOString(),
        updatedAt: new Date('2024-01-15').toISOString()
    },
    {
        id: '2',
        name: 'Smartphone',
        description: 'Latest smartphone with advanced features',
        price: 899.99,
        image: '/images/smartphone.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'smartphone-pro',
        featured: true,
        onSale: false,
        rating: 4.9,
        reviewCount: 78,
        stock: 8,
        createdAt: new Date('2024-01-16').toISOString(),
        updatedAt: new Date('2024-01-16').toISOString()
    },
    {
        id: '3',
        name: '4K Smart TV',
        description: 'Ultra HD Smart TV with vibrant colors and smart features',
        price: 1299.99,
        originalPrice: 1599.99,
        image: '/images/smart-tv.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: '4k-smart-tv',
        featured: true,
        onSale: true,
        rating: 4.7,
        reviewCount: 32,
        stock: 5,
        createdAt: new Date('2024-01-17').toISOString(),
        updatedAt: new Date('2024-01-17').toISOString()
    },
    {
        id: '4',
        name: 'Bluetooth Speaker',
        description: 'Portable Bluetooth speaker with deep bass',
        price: 99.99,
        image: '/images/bluetooth-speaker.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'bluetooth-speaker',
        featured: false,
        onSale: false,
        rating: 4.4,
        reviewCount: 24,
        stock: 20,
        createdAt: new Date('2024-01-18').toISOString(),
        updatedAt: new Date('2024-01-18').toISOString()
    },
    {
        id: '5',
        name: 'Laptop',
        description: 'Lightweight laptop with powerful performance',
        price: 1199.99,
        image: '/images/laptop.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'laptop',
        featured: true,
        onSale: false,
        rating: 4.6,
        reviewCount: 16,
        stock: 12,
        createdAt: new Date('2024-01-19').toISOString(),
        updatedAt: new Date('2024-01-19').toISOString()
    },
    {
        id: '6',
        name: 'Smartwatch',
        description: 'Track your fitness and receive notifications on your wrist',
        price: 249.99,
        image: '/images/smartwatch.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'smartwatch',
        featured: false,
        onSale: false,
        rating: 4.2,
        reviewCount: 8,
        stock: 30,
        createdAt: new Date('2024-01-20').toISOString(),
        updatedAt: new Date('2024-01-20').toISOString()
    },
    {
        id: '7',
        name: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with long battery life',
        price: 39.99,
        image: '/images/wireless-mouse.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'wireless-mouse',
        featured: false,
        onSale: false,
        rating: 4.1,
        reviewCount: 6,
        stock: 40,
        createdAt: new Date('2024-01-21').toISOString(),
        updatedAt: new Date('2024-01-21').toISOString()
    },
    {
        id: '8',
        name: 'Mechanical Keyboard',
        description: 'RGB backlit mechanical keyboard for gamers',
        price: 129.99,
        image: '/images/mechanical-keyboard.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'mechanical-keyboard',
        featured: true,
        onSale: false,
        rating: 4.5,
        reviewCount: 12,
        stock: 22,
        createdAt: new Date('2024-01-22').toISOString(),
        updatedAt: new Date('2024-01-22').toISOString()
    },
    {
        id: '9',
        name: 'Gaming Console',
        description: 'Next-gen gaming console with immersive graphics',
        price: 599.99,
        image: '/images/gaming-console.jpg',
        category: 'electronics',
        categoryId: '1',
        slug: 'gaming-console',
        featured: true,
        onSale: false,
        rating: 4.9,
        reviewCount: 36,
        stock: 7,
        createdAt: new Date('2024-01-23').toISOString(),
        updatedAt: new Date('2024-01-23').toISOString()
    },
    {
        id: '10',
        name: 'Cotton T-Shirt',
        description: 'Comfortable cotton t-shirt in various colors',
        price: 29.99,
        originalPrice: 39.99,
        image: '/images/tshirt.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'cotton-tshirt',
        featured: false,
        onSale: true,
        rating: 4.3,
        reviewCount: 18,
        stock: 50,
        createdAt: new Date('2024-01-24').toISOString(),
        updatedAt: new Date('2024-01-24').toISOString()
    },
    {
        id: '11',
        name: 'Denim Jeans',
        description: 'Classic slim-fit denim jeans',
        price: 59.99,
        image: '/images/jeans.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'denim-jeans',
        featured: true,
        onSale: false,
        rating: 4.7,
        reviewCount: 12,
        stock: 25,
        createdAt: new Date('2024-01-25').toISOString(),
        updatedAt: new Date('2024-01-25').toISOString()
    },
    {
        id: '12',
        name: 'Designer Hoodie',
        description: 'Premium quality hoodie with unique design',
        price: 79.99,
        image: '/images/hoodie.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'designer-hoodie',
        featured: true,
        onSale: false,
        rating: 4.7,
        reviewCount: 12,
        stock: 25,
        createdAt: new Date('2024-01-26').toISOString(),
        updatedAt: new Date('2024-01-26').toISOString()
    },
    {
        id: '13',
        name: 'Leather Jacket',
        description: 'Stylish leather jacket with modern fit',
        price: 199.99,
        image: '/images/leather-jacket.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'leather-jacket',
        featured: false,
        onSale: false,
        rating: 4.8,
        reviewCount: 8,
        stock: 10,
        createdAt: new Date('2024-01-27').toISOString(),
        updatedAt: new Date('2024-01-27').toISOString()
    },
    {
        id: '14',
        name: 'Sneakers',
        description: 'Lightweight sneakers for everyday comfort',
        price: 89.99,
        image: '/images/sneakers.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'sneakers',
        featured: true,
        onSale: false,
        rating: 4.5,
        reviewCount: 14,
        stock: 35,
        createdAt: new Date('2024-01-28').toISOString(),
        updatedAt: new Date('2024-01-28').toISOString()
    },
    {
        id: '15',
        name: 'Summer Dress',
        description: 'Elegant floral summer dress for women',
        price: 69.99,
        originalPrice: 89.99,
        image: '/images/summer-dress.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'summer-dress',
        featured: true,
        onSale: true,
        rating: 4.5,
        reviewCount: 16,
        stock: 18,
        createdAt: new Date('2024-01-29').toISOString(),
        updatedAt: new Date('2024-01-29').toISOString()
    },
    {
        id: '16',
        name: 'Wool Scarf',
        description: 'Soft wool scarf to keep you warm in winter',
        price: 24.99,
        image: '/images/scarf.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'wool-scarf',
        featured: false,
        onSale: false,
        rating: 4.3,
        reviewCount: 10,
        stock: 40,
        createdAt: new Date('2024-01-30').toISOString(),
        updatedAt: new Date('2024-01-30').toISOString()
    },
    {
        id: '17',
        name: 'Baseball Cap',
        description: 'Adjustable cotton cap for casual wear',
        price: 19.99,
        image: '/images/cap.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'baseball-cap',
        featured: false,
        onSale: false,
        rating: 4.0,
        reviewCount: 6,
        stock: 60,
        createdAt: new Date('2024-01-31').toISOString(),
        updatedAt: new Date('2024-01-31').toISOString()
    },
    {
        id: '18',
        name: 'Winter Coat',
        description: 'Insulated winter coat with hood',
        price: 179.99,
        image: '/images/winter-coat.jpg',
        category: 'clothing',
        categoryId: '2',
        slug: 'winter-coat',
        featured: true,
        onSale: false,
        rating: 4.6,
        reviewCount: 8,
        stock: 14,
        createdAt: new Date('2024-02-01').toISOString(),
        updatedAt: new Date('2024-02-01').toISOString()
    },
    {
        id: '19',
        name: 'Garden Tools Set',
        description: 'Complete set of gardening tools',
        price: 149.99,
        originalPrice: 199.99,
        image: '/images/garden-tools.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'garden-tools-set',
        featured: true,
        onSale: true,
        rating: 4.8,
        reviewCount: 12,
        stock: 10,
        createdAt: new Date('2024-02-02').toISOString(),
        updatedAt: new Date('2024-02-02').toISOString()
    },
    {
        id: '20',
        name: 'Scented Candle Set',
        description: 'Luxury scented candles in elegant packaging',
        price: 34.99,
        image: '/images/scented-candle.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'scented-candle-set',
        featured: true,
        onSale: false,
        rating: 4.6,
        reviewCount: 10,
        stock: 30,
        createdAt: new Date('2024-02-03').toISOString(),
        updatedAt: new Date('2024-02-03').toISOString()
    },
    {
        id: '21',
        name: 'Decorative Plant',
        description: 'Artificial decorative plant in ceramic pot',
        price: 29.99,
        image: '/images/decorative-plant.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'decorative-plant',
        featured: false,
        onSale: false,
        rating: 4.2,
        reviewCount: 8,
        stock: 25,
        createdAt: new Date('2024-02-04').toISOString(),
        updatedAt: new Date('2024-02-04').toISOString()
    },
    {
        id: '22',
        name: 'Wall Clock',
        description: 'Minimalist wall clock for living room',
        price: 39.99,
        image: '/images/wall-clock.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'wall-clock',
        featured: false,
        onSale: false,
        rating: 4.3,
        reviewCount: 9,
        stock: 20,
        createdAt: new Date('2024-02-05').toISOString(),
        updatedAt: new Date('2024-02-05').toISOString()
    },
    {
        id: '23',
        name: 'Coffee Maker Deluxe',
        description: 'Automatic drip coffee maker with timer and grinder',
        price: 89.99,
        originalPrice: 129.99,
        image: '/images/coffee-maker.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'coffee-maker-deluxe',
        featured: false,
        onSale: true,
        rating: 4.4,
        reviewCount: 11,
        stock: 15,
        createdAt: new Date('2024-02-06').toISOString(),
        updatedAt: new Date('2024-02-06').toISOString()
    },
    {
        id: '24',
        name: 'Vacuum Cleaner',
        description: 'Powerful cordless vacuum cleaner',
        price: 249.99,
        image: '/images/vacuum-cleaner.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'vacuum-cleaner',
        featured: true,
        onSale: false,
        rating: 4.5,
        reviewCount: 14,
        stock: 18,
        createdAt: new Date('2024-02-07').toISOString(),
        updatedAt: new Date('2024-02-07').toISOString()
    },
    {
        id: '25',
        name: 'Cookware Set',
        description: 'Non-stick cookware set for everyday use',
        price: 179.99,
        image: '/images/cookware-set.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'cookware-set',
        featured: true,
        onSale: false,
        rating: 4.7,
        reviewCount: 16,
        stock: 12,
        createdAt: new Date('2024-02-08').toISOString(),
        updatedAt: new Date('2024-02-08').toISOString()
    },
    {
        id: '26',
        name: 'Table Lamp',
        description: 'Modern LED table lamp with adjustable brightness',
        price: 49.99,
        image: '/images/table-lamp.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'table-lamp',
        featured: false,
        onSale: false,
        rating: 4.3,
        reviewCount: 7,
        stock: 28,
        createdAt: new Date('2024-02-09').toISOString(),
        updatedAt: new Date('2024-02-09').toISOString()
    },
    {
        id: '27',
        name: 'Rug Carpet',
        description: 'Soft rug carpet for your living space',
        price: 99.99,
        image: '/images/rug.jpg',
        category: 'home-garden',
        categoryId: '3',
        slug: 'rug-carpet',
        featured: true,
        onSale: false,
        rating: 4.6,
        reviewCount: 13,
        stock: 10,
        createdAt: new Date('2024-02-10').toISOString(),
        updatedAt: new Date('2024-02-10').toISOString()
    },
];